name: Coverage

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11

jobs:
  generate-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.path ~/.virtualenvs${{ env.PYTHON_VERSION }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install -E minify

      - name: Generate coverage badge
        run: |
          chmod +x generate_badge.sh
          ./generate_badge.sh

      - name: Commit and push coverage badge
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b py-code-coverage || git checkout py-code-coverage
          git pull origin py-code-coverage
          git add .
          git commit -m "Update coverage badge"
          git push --force origin py-code-coverage
